/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
          "error": "#ba1a1a",
          "surface-dim": "#cbdbf5",
          "on-surface-variant": "#3f4a3e",
          "on-secondary-fixed-variant": "#3f465c",
          "on-primary": "#ffffff",
          "surface-container-low": "#eff4ff",
          "inverse-on-surface": "#eaf1ff",
          "secondary": "#565e74",
          "background": "#f8f9ff",
          "on-tertiary-fixed-variant": "#444749",
          "on-tertiary-fixed": "#191c1e",
          "primary": "#005e26",
          "tertiary-fixed": "#e0e3e5",
          "secondary-fixed": "#dae2fd",
          "on-background": "#0b1c30",
          "tertiary": "#4e5254",
          "error-container": "#ffdad6",
          "inverse-surface": "#213145",
          "on-primary-container": "#a1ffad",
          "secondary-fixed-dim": "#bec6e0",
          "on-secondary": "#ffffff",
          "on-error-container": "#93000a",
          "surface-container-high": "#dce9ff",
          "tertiary-fixed-dim": "#c4c7c9",
          "outline-variant": "#becabb",
          "surface": "#f8f9ff",
          "secondary-container": "#dae2fd",
          "outline": "#6f7a6d",
          "primary-fixed-dim": "#77dc88",
          "on-primary-fixed": "#002109",
          "inverse-primary": "#77dc88",
          "on-secondary-container": "#5c647a",
          "surface-container-highest": "#d3e4fe",
          "surface-bright": "#f8f9ff",
          "on-tertiary-container": "#e8eaec",
          "on-error": "#ffffff",
          "on-tertiary": "#ffffff",
          "primary-container": "#007a33",
          "surface-container": "#e5eeff",
          "on-primary-fixed-variant": "#005320",
          "primary-fixed": "#93f9a2",
          "on-surface": "#0b1c30",
          "tertiary-container": "#676a6c",
          "surface-container-lowest": "#ffffff",
          "surface-tint": "#006e2d",
          "on-secondary-fixed": "#131b2e",
          "surface-variant": "#d3e4fe"
      },
      "borderRadius": {
          "DEFAULT": "0.125rem",
          "sm": "0.125rem",
          "md": "0.25rem",
          "lg": "0.25rem",
          "xl": "0.5rem",
          "full": "0.75rem",
          "soft": "0.25rem",
          "search": "0.5rem"
      },
      "spacing": {
          "margin-mobile": "16px",
          "gutter": "16px",
          "unit": "4px",
          "max-width": "1440px",
          "margin-desktop": "48px"
      },
      "fontFamily": {
          "sans": ["Inter", "sans-serif"],
          "label-caps": ["Inter", "sans-serif"],
          "body-sm": ["Inter", "sans-serif"],
          "body-lg": ["Inter", "sans-serif"],
          "headline-lg-mobile": ["Inter", "sans-serif"],
          "title-md": ["Inter", "sans-serif"],
          "display-lg": ["Inter", "sans-serif"],
          "headline-lg": ["Inter", "sans-serif"]
      },
      "fontSize": {
          "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
          "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
          "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
          "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
          "title-md": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
          "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
          "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
