# Generated by Django 6.0.4 on 2026-05-27 14:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Version. Example: v1.0.0', max_length=20, unique=True)),
                ('content', models.TextField(help_text='Full text of the privacy policy')),
                ('effective_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Privacy Policies',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('aplica_impuesto', models.BooleanField(default=True, verbose_name='¿Aplica Impuesto?')),
                ('is_activo', models.BooleanField(default=True, verbose_name='¿Está Activo?')),
                ('vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('categoria', models.CharField(choices=[('AGRICOLA', 'Agrícola'), ('INSTITUCIONAL', 'Institucional'), ('TECNOLOGICO', 'Tecnológico'), ('ACADEMICO', 'Académico'), ('TEXTIL', 'Textil'), ('SOUVENIR', 'Souvenir'), ('TEMPORAL', 'Temporal')], default='SOUVENIR', max_length=20, verbose_name='Categoría')),
                ('medida', models.CharField(choices=[('GRAMO', 'Gramo'), ('KILOGRAMO', 'Kilogramo'), ('LIBRA', 'Libra'), ('UNIDAD', 'Unidad')], default='UNIDAD', max_length=15, verbose_name='Medida')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('imagen_url', models.URLField(blank=True, null=True, verbose_name='URL de Imagen Externa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('nombre_completo', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('identificacion', models.CharField(blank=True, max_length=20, verbose_name='Identificación')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('CLIENTE', 'Cliente'), ('CAJERO', 'Cajero'), ('BODEGUERO', 'Bodeguero'), ('GERENTE', 'Gerente'), ('SUPERVISOR', 'Supervisor')], default='CLIENTE', max_length=15, verbose_name='Rol')),
                ('is_universidad', models.BooleanField(default=False, verbose_name='¿Es de la Universidad?')),
                ('consentimiento_lopdp', models.BooleanField(default=False, help_text='Explicit consent to data processing under LOPDP')),
                ('consentimiento_timestamp', models.DateTimeField(blank=True, help_text='When the consent was given', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('privacy_policy', models.ForeignKey(blank=True, help_text='The privacy policy version accepted', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='tienda.privacypolicy')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_abre', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierra', models.DateTimeField(blank=True, null=True)),
                ('saldo_abre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_cierra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cajero', models.ForeignKey(limit_choices_to={'rol': 'CAJERO'}, on_delete=django.db.models.deletion.RESTRICT, related_name='cajas_gestionadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(help_text='Generado automáticamente. Formato: P-YYYYMMDD-XXX', max_length=20, unique=True, verbose_name='Número de Pedido')),
                ('estado', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('PREPARACION', 'En Preparación'), ('LISTO', 'Listo'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado'), ('DEVOLUCION', 'Devolución')], default='RECIBIDO', max_length=20, verbose_name='Estado del Pedido')),
                ('tipo_entrega', models.CharField(choices=[('TIENDA', 'Tienda'), ('DOMICILIO', 'Domicilio')], default='TIENDA', max_length=15, verbose_name='Tipo de Entrega')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Subtotal')),
                ('impuesto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Impuesto (IVA)')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('is_use', models.BooleanField(default=True)),
                ('productos', models.ManyToManyField(related_name='promociones', to='tienda.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('DEBITO', 'Débito'), ('CREDITO', 'Crédito')], default='EFECTIVO', max_length=20)),
                ('cajero', models.ForeignKey(limit_choices_to={'rol': 'CAJERO'}, on_delete=django.db.models.deletion.RESTRICT, related_name='ventas_registradas', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venta', to='tienda.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(help_text='Snapshot del nombre al momento de la venta', max_length=255, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('cantidad', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio pagado por unidad (histórico)', max_digits=10, verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, help_text='cantidad * precio_unitario', max_digits=10, verbose_name='Subtotal')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.producto', verbose_name='Producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='tienda.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['numero_pedido'], name='tienda_pedi_numero__974059_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['cliente', '-fecha_creacion'], name='tienda_pedi_cliente_66eda3_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado'], name='tienda_pedi_estado_9912bc_idx'),
        ),
    ]
