# Generated by Django 6.0.4 on 2026-05-27 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_detalleventa_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_venta', to='tienda.pedido', verbose_name='Pedido'),
        ),
    ]
