# Generated by Django 6.0.4 on 2026-06-14 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_detalleventa_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='venta',
        ),
    ]
