# Generated by Django 6.0.4 on 2026-06-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_transaccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen_url',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='vencimiento',
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_caducidad',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Caducidad'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_llegada',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Llegada'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen del Producto'),
        ),
    ]
