# Generated by Django 6.0.4 on 2026-06-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_remove_producto_imagen_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='comunidad_rol',
            field=models.CharField(blank=True, max_length=50, verbose_name='Rol en la Comunidad UNL'),
        ),
    ]
