# Generated by Django 6.0.4 on 2026-06-22 02:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_usuario_comunidad_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Cantidad'),
        ),
        migrations.CreateModel(
            name='ProductoVariacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Talla S, Kilo, Unidad', max_length=50, verbose_name='Nombre de Variación')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock de Variación')),
                ('precio_adicional', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Adicional')),
                ('precio_fijo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Fijo Override')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variaciones', to='tienda.producto')),
            ],
            options={
                'verbose_name': 'Variación de Producto',
                'verbose_name_plural': 'Variaciones de Producto',
            },
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='variacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.productovariacion', verbose_name='Variación Seleccionada'),
        ),
    ]
