# Generated by Django 6.0.4 on 2026-06-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('AGRICOLA', 'Agrícola'), ('INSTITUCIONAL', 'Institucional'), ('TECNOLOGICO', 'Tecnológico'), ('ACADEMICO', 'Académico'), ('TEXTIL', 'Textil'), ('SOUVENIR', 'Souvenir'), ('TEMPORAL', 'Temporal'), ('HORTALIZAS', 'Hortalizas'), ('FRUTAS', 'Frutas'), ('CARNES', 'Carnes'), ('LACTEOS', 'Lácteos'), ('BEBIDAS', 'Bebidas')], default='SOUVENIR', max_length=20, verbose_name='Categoría'),
        ),
    ]
