# Generated by Django 6.0.4 on 2026-07-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_migrate_legacy_food_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('PENDIENTE_RETIRO', 'Pendiente a Retirar'), ('PREPARACION', 'En Preparación'), ('LISTO', 'Listo'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado'), ('DEVOLUCION', 'Devolución')], default='RECIBIDO', max_length=20, verbose_name='Estado del Pedido'),
        ),
    ]
