project:
  type: website
  output-dir: _site

website:
  title: "Docs - Tienda Universitaria"
  description: "Documentación oficial de la Tienda Universitaria (Backend & Frontend)"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Inicio"
        contents:
          - index.qmd
          - setup.qmd
          - integracion-frontend-backend.qmd
          - dockerizacion.qmd
      - section: "Seguridad y Autenticación"
        contents:
          - autenticacion-jwt.qmd
          - seguridad-tokens.qmd
      - section: "Especificaciones de Negocio"
        contents:
          - specs.qmd
          - catalogo-productos.qmd
          - ordenes-pedidos.qmd
      - section: "Referencia API REST"
        contents:
          - api.qmd
      - section: "Análisis y Cobertura (QA)"
        contents:
          - testing.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
